[package]
name = "from_object_to_functions"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum = "0.8.3"
bytes = "1.10.1"
reqwest = "0.12.15"
regex = "1.11.1"
indoc = "2"
once_cell = "1.19"